baseURL: https://glucn.github.io/
languageCode: en-us
title: glucn's blog
theme: "PaperMod"
paginate: 10

googleAnalytics: UA-130792560-1
enableRobotsTXT: true
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

params:
  env: production # to enable Google Analytics, opengraph, twitter-cards and schema.
  defaultTheme: auto

  homeInfoParams:
    Title: "ðŸ‘‹ Welcome to glucn's blog"
    Content: >
      This is Gary. I consider this blog as my vault of knowledge, hope you will find something useful here. Other than writing blogs, I'm a SDE at AWS.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/gary-yue-lu"
    - name: github
      url: "https://github.com/glucn"
    - name: twitter
      url: "https://twitter.com/gary_luy/"
    - name: kaggle
      url: "https://www.kaggle.com/garylucn"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20

markup:
  highlight:
    style: native

outputs:
    home:
        - HTML
        - RSS
        - JSON # necessary for search